"""add mobile devices and events

Revision ID: 2a89955a4e57
Revises: ed78ad080996
Create Date: 2026-09-25 20:54:56.484301
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2a89955a4e57'
down_revision: Union[str, None] = 'ed78ad080996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('mobile_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('source_package', sa.String(length=180), nullable=False),
    sa.Column('source_label', sa.String(length=100), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_requests.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_events_analysis_id'), 'mobile_events', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_mobile_events_device_id'), 'mobile_events', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobile_events_device_id'), table_name='mobile_events')
    op.drop_index(op.f('ix_mobile_events_analysis_id'), table_name='mobile_events')
    op.drop_table('mobile_events')
    op.drop_table('devices')
    # ### end Alembic commands ###

