"""add ai analysis metadata and observation counts

Revision ID: 35e6352f40e8
Revises: 2a89955a4e57
Create Date: 2026-09-26 01:23:38.628622
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '35e6352f40e8'
down_revision: Union[str, None] = '2a89955a4e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_requests', sa.Column('ai_provider', sa.String(length=32), nullable=True))
    op.add_column('analysis_requests', sa.Column('ai_model', sa.String(length=80), nullable=True))
    op.add_column('analysis_requests', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('analysis_requests', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('threat_indicators', sa.Column('observation_count', sa.Integer(), nullable=False, server_default='1'))
    demo_message = "Your electricity connection will be disconnected tonight. Pay ₹4980 immediately at ramesh123@oksbi using https://electric-bill-secure.xyz"
    connection = op.get_bind()
    demo_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM analysis_requests WHERE input_text = :message"), {"message": demo_message})]
    if demo_ids:
        session_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM honeypot_sessions WHERE analysis_id IN :ids").bindparams(sa.bindparam("ids", expanding=True)), {"ids": demo_ids})]
        if session_ids:
            connection.execute(sa.text("DELETE FROM honeypot_messages WHERE session_id IN :ids").bindparams(sa.bindparam("ids", expanding=True)), {"ids": session_ids})
            connection.execute(sa.text("DELETE FROM honeypot_sessions WHERE id IN :ids").bindparams(sa.bindparam("ids", expanding=True)), {"ids": session_ids})
        connection.execute(sa.text("DELETE FROM analysis_requests WHERE id IN :ids").bindparams(sa.bindparam("ids", expanding=True)), {"ids": demo_ids})
    # Remove the exact records created by the retired demo seeder. User-submitted data is untouched.
    op.execute("DELETE FROM campaign_indicators WHERE campaign_id IN ('campaign-17', 'campaign-23')")
    op.execute("DELETE FROM threat_edges WHERE source_id LIKE 'ind-%' OR target_id LIKE 'ind-%'")
    op.execute("DELETE FROM campaigns WHERE id IN ('campaign-17', 'campaign-23')")
    op.execute("DELETE FROM threat_indicators WHERE id LIKE 'ind-%'")
    op.execute("""
        DELETE FROM scam_reports WHERE
        (phone_number = '+91 98765 43210' AND upi_id = 'ramesh123@oksbi' AND url = 'https://electric-bill-secure.xyz') OR
        (phone_number = '+91 91234 56780' AND upi_id = 'ramesh123@oksbi' AND message = 'Outstanding power bill. Pay immediately') OR
        (upi_id = 'kycdesk@okaxis' AND url = 'https://sbi-kyc-secure.top' AND message = 'SBI KYC expired, update now')
    """)
    op.execute("DELETE FROM scam_reports WHERE COALESCE(phone_number, '') = '' AND COALESCE(upi_id, '') = '' AND COALESCE(url, '') = '' AND TRIM(message) = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threat_indicators', 'observation_count')
    op.drop_column('analysis_requests', 'ai_confidence')
    op.drop_column('analysis_requests', 'ai_summary')
    op.drop_column('analysis_requests', 'ai_model')
    op.drop_column('analysis_requests', 'ai_provider')
    # ### end Alembic commands ###
