import { FormEvent, useEffect, useState } from 'react'
import { useLocation, useParams } from 'react-router-dom'
import { Bot, CheckCircle2, Send, ShieldCheck, Sparkles } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { ErrorBlock, LoadingBlock } from '../components/StateBlock'
import { api } from '../lib/api'

export default function Honeypot() {
  const { id = '' } = useParams(); const location = useLocation(); const [session, setSession] = useState<any>(location.state || null); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!session) api.honeypot(id).then(setSession).catch(err => setError(err.message)) }, [id, session])
  const send = async (event: FormEvent) => { event.preventDefault(); if (!input.trim()) return; setLoading(true); setError(''); try { setSession(await api.sendHoneypot(id, input)); setInput('') } catch (err) { setError(err instanceof Error ? err.message : 'Message failed') } finally { setLoading(false) } }
  if (error && !session) return <div className="page"><ErrorBlock message={error} /></div>; if (!session) return <div className="page"><LoadingBlock /></div>
  const intel = session.intelligence || {}
  const canaryLabel = session.canary?.proposed ? 'Proposed in reply' : session.canary?.armed ? 'Armed · waiting' : session.canary?.configured ? 'Available · not armed' : 'Not configured'
  return <div className="page"><PageHeader eyebrow="DECEIVE / CONTROLLED SIMULATION" title="Gemini defensive honeypot" description="A synthetic victim persona keeps the scammer talking long enough to collect voluntarily shared indicators." action={<span className={`session-state ${session.active ? 'active' : ''}`}><i />{session.active ? 'Session active' : 'Complete'}</span>} /><div className="honeypot-grid"><section className="panel chat-panel"><div className="chat-safety"><ShieldCheck size={16} /><span>No OTPs, passwords, private victim data, payments, automatic link opening, or unauthorized access.</span></div><div className="chat-stream">{session.messages.map((message: any) => <div className={`chat-message ${message.role}`} key={message.id}><div className="chat-avatar">{message.role === 'assistant' ? <Bot size={17} /> : 'S'}</div><div><span>{message.role === 'assistant' ? 'NAZAR synthetic victim' : 'Scammer message'}</span><p>{message.content}</p></div></div>)}</div><form className="chat-input" onSubmit={send}><textarea value={input} onChange={event => setInput(event.target.value)} placeholder="Paste the scammer’s next message…" rows={2} disabled={!session.active} /><button className="button primary" disabled={loading || !session.active}><Send size={17} />{loading ? 'Gemini is composing…' : 'Generate safe reply'}</button></form>{error && <p className="inline-error">{error}</p>}</section><aside className="panel intel-panel"><div className="panel-heading"><div><span className="panel-kicker">LIVE EXTRACTION</span><h2>Intelligence collected</h2></div><Sparkles size={19} /></div><div className="state-machine"><span>Reply engine</span><strong>{session.reply_engine?.startsWith('gemini') ? 'Gemini' : session.gemini_available ? 'Safety fallback' : 'Safety fallback · add Gemini key'}</strong></div><div className="state-machine"><span>Canary beacon</span><strong>{canaryLabel}</strong></div><div className="state-machine"><span>Current state</span><strong>{session.state.replaceAll('_', ' ')}</strong><div><i style={{ width: `${Math.min(100, (['INITIAL_CONTACT','BUILD_TRUST','DELAY_PAYMENT','COLLECT_PAYMENT_IDENTIFIER','COLLECT_URL','COLLECT_ALTERNATIVE_CONTACT','IDENTIFY_SCAM_SCRIPT','COMPLETE'].indexOf(session.state) + 1) * 12.5)}%` }} /></div></div><div className="intel-list">{['upi_ids','urls','phone_numbers','amounts','claimed_organizations','tactics'].map(key => <div key={key}><span>{key.replaceAll('_', ' ')}</span>{intel[key]?.length ? intel[key].map((value: unknown) => <b key={String(value)}><CheckCircle2 size={14} />{String(value)}</b>) : <em>Waiting for signal</em>}</div>)}</div></aside></div></div>
}
