import { FormEvent, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { CheckCircle2, Send } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { api } from '../lib/api'

export default function Report() {
  const location = useLocation(); const analysis: any = (location.state as any)?.analysis; const entities = analysis?.entities || {}
  const [form, setForm] = useState({ phone_number: entities.phone_numbers?.[0] || '', upi_id: entities.upi_ids?.[0] || '', url: entities.urls?.[0] || '', message: '', scam_category: analysis?.category || 'payment_request_scam' }); const [loading, setLoading] = useState(false); const [result, setResult] = useState(''); const [error, setError] = useState('')
  const update = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await api.report(form); setResult(response.message) } catch (err) { setError(err instanceof Error ? err.message : 'Report failed') } finally { setLoading(false) } }
  return <div className="page narrow-page"><PageHeader eyebrow="SHARE / COMMUNITY" title="Report a scam signal" description="Your report can connect a phone number, UPI ID or domain to an existing campaign. Do not include passwords, OTPs or private victim data." /><form className="panel report-form" onSubmit={submit}>{result ? <div className="success-card"><CheckCircle2 size={30} /><h2>Report received</h2><p>{result}. Thank you for strengthening the community signal.</p><button type="button" className="button secondary" onClick={() => setResult('')}>Report another</button></div> : <><div className="form-grid two"><label className="field"><span>Phone number</span><input value={form.phone_number} onChange={event => update('phone_number', event.target.value)} placeholder="+91 98765 43210" /></label><label className="field"><span>UPI ID</span><input value={form.upi_id} onChange={event => update('upi_id', event.target.value)} placeholder="name@bank" /></label></div><label className="field"><span>URL or domain</span><input value={form.url} onChange={event => update('url', event.target.value)} placeholder="https://suspicious.example" /></label><label className="field"><span>Message received</span><textarea rows={6} value={form.message} onChange={event => update('message', event.target.value)} placeholder="Paste the scam message, removing any private information…" /></label><label className="field"><span>Scam category</span><select value={form.scam_category} onChange={event => update('scam_category', event.target.value)}>{['phishing','fake_kyc','bank_impersonation','utility_scam','fake_reward','investment_scam','delivery_scam','job_scam','payment_request_scam'].map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label>{error && <p className="inline-error">{error}</p>}<div className="form-actions"><span>Reports are stored as defensive threat intelligence.</span><button className="button primary" disabled={loading}><Send size={17} />{loading ? 'Submitting…' : 'Submit report'}</button></div></>}</form></div>
}

